version: "3.8"

services:
    laravel:
        #env_file: ".env"
        image: kooldev/php:8.1-nginx
        volumes:
            - ./${LARAVEL_PATH}:/app
        environment:
          ASUSER: "${UID}"
        ports:
            - "8000:80"
        networks:
            - laravel-network
    db:
        image: mariadb:10.11
        restart: always
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        command: [
            '--character-set-server=utf8mb4',
            '--collation-server=utf8mb4_unicode_ci',
            '--default-authentication-plugin=mysql_native_password'
        ]
        volumes:
            - ./database/dbdata:/var/lib/mysql
        networks:
            - laravel-network

networks:
    laravel-network:
